### ISSUE TITLE
translate README.md to english

### ISSUE THREAD

**Issue by JoaoCarabetta** [CTS-FGV/corrupcao_analise#1]

**Comment by lucasfariaslf** [comment]
@JoaoCarabetta sure! thought only `geral` was to be maintained in English. 

_Sent from my Motorola XT1097 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lucasfariaslf** [comment]
done.

**Comment by lucasfariaslf** [comment]
done.
